---
abstract: 'Perl interface to the HabitRPG API'
author:
  - 'Paul Fenwick <pjf@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300030, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-HabitRPG
requires:
  Config::Tiny: 0
  Data::Dumper: 0
  File::Spec: 0
  JSON::Any: 0
  LWP::Protocol::https: 0
  Method::Signatures: 0
  Moo: 0
  WWW::Mechanize: 0
  WebService::Idonethis: 0
  autodie: 0
  perl: v5.10.0
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/pjf/WebService-HabitRPG.git
version: 0.08
